### ISSUE TITLE
Cannot mount cephfs

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/somerville-operations#99] opened 2023-05-09 09:41 UTC
Lasair-ztf webserver was down this morning 'Service Unavailable". Logged in and could get no response from cephFS -- `df` and `ls -l /mnt` and `sudo mount /mnt/cephfs` all hang. Did soft reboot from somerville dashboard.  And still all the above commands hang.

**Comment by RoyWilliams** [comment] 2023-05-09 12:44
Lasair website down now for 9 hours. Getting complaints.

**Comment by GregBlow** [comment] 2023-05-09 13:06
Noted, will look into this afternoon.

**Comment by astrodb** [comment] 2023-05-09 13:13
Ceph system is unhappy. Reported crash this morning, and I've been looking into it in between other things since then. Wasn't aware it had frozen all CephFS connections though, good ot know.

**Comment by astrodb** [comment] 2023-05-09 13:43
Just to confirm, this appears to be a Ceph bug (same a occured a couple weeks ago). We are working on a fix.

**Comment by astrodb** [comment] 2023-05-10 08:05
We believe the issue is another reoccurance of this bug: https://tracker.ceph.com/issues/48673 
The system is currently back online after some fixes. (for the record, we had to stop and restart the full cephfs system: ceph fs fail cephfs & ceph fs set cephfs joinable true )

The bug is expected to be resolved in the next version of Ceph, which we are upgrading to today.

**Comment by genghisken** [comment] 2023-05-12 13:32
Hi all - any progress on the CephFS problem. Lasair still can't see the Ceph mounts, so the problem is not resolved, or has recurred.

**Comment by astrodb** [comment] 2023-05-12 13:56
It has reoccured, so it looks like the bug isn't fixed in the upgraded version of Ceph. And something about the Lasair use-pattern is causing it to fall over.

**Comment by RoyWilliams** [comment] 2023-05-12 14:57
My summary of today
- 09:16 Trouble starts. See attached from mod_wsgi error.log
  Timeout when reading response headers from daemon process
- 11:15 Michael complains of a 503 service error on web server
- 11:24 New kind of error message in error.log
  Queue timeout expired for WSGI daemon process
- 11:25 Roy notices several stuck processes dating from 09:15
    trying to create an existing directory /mnt/cephfs/lasair/fits
    also notes webserver has load average of 6
- 11:26 Roy kills the zombie mkdirs
- 11:30 The zombie mkdir processes are back dating from 11:26
- 11:53 Ken tried to restart the web but ceph hangs
- 14:10 Comment out the line in the code that does these repeated mkdir
  Soft reboot the webserver
  Webserver comes up, but ceph still broken

[lasair error log.txt](https://github.com/lsst-uk/somerville-operations/files/11465396/lasair.error.log.txt)

**Comment by astrodb** [comment] 2023-05-12 14:59
Can you post the /vasr/log/syslog file from the VM here? That should contain the kernel client error messages.

**Comment by RoyWilliams** [comment] 2023-05-12 15:00
- There is a process that does `mkdir /mnt/cephfs/lasair/fits` 1000s of times. 
- Note in the above that first sign of trouble was at 09:16 UTC -- exactly the same as the timestamp on the leftover zombie mkdirs.
- I have removed this redundant call from the code and want to try again, see if the webserver can stay up for a few days.

**Comment by RoyWilliams** [comment] 2023-05-12 15:03
[syslog.txt](https://github.com/lsst-uk/somerville-operations/files/11465460/syslog.txt)

**Comment by astrodb** [comment] 2023-05-12 15:56
System is fixed for the moment.

For the record, commands were:
`ceph fs fail cephfs`
`ceph orch daemon stop mon.sv-hdd-12-1`   (this needs to be the mon leader, found by running `ceph mon stat`
....waiting for the mon to shutdown....
`ceph fs set cephfs joinable true`
`ceph orch daemon start mon.sv-hdd-12-1`

**Comment by astrodb** [comment] 2023-05-15 09:21
CephFS appears to be up and happy over the weekend. Did ingests run?

**Comment by RoyWilliams** [comment] 2023-05-15 10:39
Lasair started up Friday 16:00 and has been happy since then, ingestion has been running since Sunday morning, load averages are low, nothing bad in the web error log. The only change is that the [spurious mkdir](https://github.com/lsst-uk/lasair4/blob/main/common/src/objectStore.py#L19) has been removed everywhere -- it is my hunch that this was part of the problem, as I found several zombie mkdir processes that started at the same time on Friday morning that the error log started looking bad.

**Closed as completed** 2023-06-12 13:26 UTC
