### ISSUE TITLE
Port 5000 fw issue

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#45] opened 2022-10-04 13:16 UTC
Port 5000 does not appear to be externally accessible which stops IAM login to Horizon from working.

**Comment by astrodb** [comment] 2022-10-04 13:19
Worth noting that I don't see this problem from home, and my IP should appear as a "random" ISP provided address (I'm on ROE VPN, but it is set to only route on roe.ac.uk addresses).

It's possible this is getting filtered somewhere upstream. I recommend interactive testing with @gpfrancis while watching the logs on the Horizon service, the service host, and the ACF firewall to see where the packets are getting dropped.

**Comment by GregBlow** [comment] 2022-10-04 22:17
I've requested port 5000 only be moved back to be internet accessible:

1) presently on leave, delaying work on this. Better to revert and plan testing
2) I observe the same thing Gareth does on my own home internet, from ACF VPN IRIS IAM is working
3) entering a period before I return from leave where changes to firewall will be difficult
4) all other aspects of API remain behind firewall, I think this represents the implementation closest to intention. 

From this it looks like the user's own address is used by IRIS IAM to authenticate

**Comment by GregBlow** [comment] 2022-10-14 10:50
Closing as intended design until policy review.

**Closed by GregBlow** 2022-10-14 10:50 UTC
