### ISSUE TITLE
Heat stack create/update issue

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#66] opened 2022-12-05 15:53 UTC
Attempting to create or update a heat stack for Lasair usually fails with an error message similar to this:
```
"Failure in updating stack: Resource CREATE failed: BadRequest: resources.kafka_pub.resources.srv: Block Device Mapping is Invalid: failed to get volume 8b4a8bb3-ab59-439b-acf7-9f5199f4ed2a. (HTTP 400) (Request-ID: req-340a84c6-10a8-44eb-8f5d-52695391865a)"
```

Creating an empty stack with no instances appears to work fine.

Updating the stack to add instances appears to work if the instances spawn quickly, but fail if they take a long time to spawn (even though they do ultimately do so).

Adding instances one at a time to an empty stack and finding that ~25% of the time the instance takes about 1min to spawn and the addition works; the rest of the time the instances takes >5 min to spawn and the addition fails. Failed additions can be rolled back OK and retried. There does not appear to be any correlation between instance type or group and either how long it takes to spawn or whether the update works.

1. Why is it taking so long to spawn instances most of the time?
2. But not always?
3. This feels like a ~5min timeout in heat. Is it?

**Comment by astrodb** [comment] 2023-01-06 11:19
Troubleshooting chat from Slack:

The log of what we tried is in a thread in #rubin-science-platform in the LSST:UK slack.
11:31
Quick summary: as of early autumn, Magnum appeared to be working. Stelios and I both had clusters deployed in the RSP project using a copy of the template that we got from Piotr.
11:32
In December, things did not seem to be working. I tried resizing my cluster to add more workers and it ended up in state "UPDATE_FAILED"
11:32
I tried to delete and recreate the cluster and the create failed
11:33
Eventually 
@Mark Holliman
 and I were able to find time to work through an attempted deployment together just before the holidays
11:34
We verified that using the template that had previously worked now failed with what looked like networking related errors
11:37
We found that adding the parameter 'fixed_subnet_cidr': '10.71.0.0/24' to the template seemed to help. Perhaps there is a conflict if multiple clusters all try to use the default 10.0.0.0/24 subnet. Although why this should have worked previously and then stopped I don't know.
11:37
However, the deployment is still failing.
11:38
It is also taking a long time to get to the failed state which makes debugging slow work.

**Comment by astrodb** [comment] 2023-01-06 11:20
And to reproduce:

The two cluster templates I was using were gf-test e5024c2a-2f1c-4f7c-9409-a1e132038c45  and gf-test-2 e8cbf656-4505-4f3b-afbf-f8c2a1ea5452 both in the RSP project.
12:03
The Heat create/update issue relates to the Lasair project. I was using this template: https://github.com/lsst-uk/lasair-deploy/blob/develop/heat_template.yaml although I would suggest using something smaller and simpler for debugging.

**Comment by gpfrancis** [comment] 2023-01-06 11:26
Comment from the user liason meeting: the Heat and Magnum issues may well have a common cause so it may make sense technically to work on the Heat issue first, but from a user POV getting Magnum working is actually slightly more urgent.

**Comment by GregBlow** [comment] 2023-01-31 16:32
[server_with_volume.yaml](https://github.com/lsst-uk/lasair-deploy/blob/develop/server_with_volume.yaml)

**Comment by GregBlow** [comment] 2023-01-31 16:32
[lasair_problem_heat.txt](https://github.com/lsst-uk/somerville-operations/files/10548706/lasair_problem_heat.txt)

**Comment by GregBlow** [comment] 2023-01-31 16:51
errors appear to be local to Kafka group resource group 

```
kafka_group:
    properties:
      count:
        get_param: n_kafka
      resource_def:
        properties:
          flavor:
            get_param: flavor_kafka
          image_id:
            get_param: image_id
          key_name:
            get_param: key_name
          net:
            get_param: net
          server_group:
            get_resource: kafka_server_group
          server_name:
            list_join:
            - '-'
            - - get_param: OS::stack_name
              - kafka
              - '%index%'
          volume_size:
            get_param: volume_small
        type: https://raw.githubusercontent.com/lsst-uk/lasair-deploy/develop/server_with_volume.yaml
    type: OS::Heat::ResourceGroup
```

**Comment by GregBlow** [comment] 2023-01-31 17:00
issue is replicated when no optional groups (create_db, create_web, etc) are selected.

**Comment by GregBlow** [comment] 2023-01-31 17:10
notable differences with other resource group only that extra_volume_size and extra_volume_type properties not present, and that flavor is different. Suggests problem is with flavor.

**Comment by GregBlow** [comment] 2023-01-31 17:31
G Francis
  [5:27 PM](https://ifaedinburghs-ofn4738.slack.com/archives/C03SK93N84C/p1675186064118329)
What I was seeing in December was that adding instances usually, but not always, took a long time and failed. No difference between different types.
[5:28](https://ifaedinburghs-ofn4738.slack.com/archives/C03SK93N84C/p1675186102010039)
What I'm seeing now is that any number of kafka instances fails, and in a different way. Some other combinations work. So something has changed at some point.
[5:30](https://ifaedinburghs-ofn4738.slack.com/archives/C03SK93N84C/p1675186231889389)
Just added three ingest instances and that works too.

**Comment by GregBlow** [comment] 2023-02-01 08:29
<html><body>


Stack Resource | Resource | Time Since Event | Status | Status Reason
-- | -- | -- | -- | --
issue-66-test-4 | 0fb3dcdd-6db6-4200-b511-5df63601906c | 14 hours, 12 minutes | Create Failed | Resource CREATE failed: Unauthorized:  resources.sherlock_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)
sherlock_group | 6f07154d-4b07-43b9-a2f9-482ddbdb8d2c | 14 hours, 12 minutes | Create Failed | Unauthorized:  resources.sherlock_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)
issue-66-test-4 | 0fb3dcdd-6db6-4200-b511-5df63601906c | 14 hours, 12 minutes | Create Failed | Resource CREATE failed: Unauthorized:  resources.cassandra_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)
cassandra_group | e5cdfb6b-118b-416d-a06c-fe8042463134 | 14 hours, 12 minutes | Create Failed | Unauthorized:  resources.cassandra_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)


</body>
</html>Stack Resource
	Resource
	Time Since Event
	Status
	Status Reason
issue-66-test-4 	0fb3dcdd-6db6-4200-b511-5df63601906c 	14 hours, 12 minutes 	Create Failed 	Resource CREATE failed: Unauthorized: resources.[sherlock_group](https://somerville.ed.ac.uk/project/stacks/stack/0fb3dcdd-6db6-4200-b511-5df63601906c/sherlock_group/).resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)
sherlock_group	6f07154d-4b07-43b9-a2f9-482ddbdb8d2c 	14 hours, 12 minutes 	Create Failed 	Unauthorized: resources.sherlock_group.resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)
issue-66-test-4 	0fb3dcdd-6db6-4200-b511-5df63601906c 	14 hours, 12 minutes 	Create Failed 	Resource CREATE failed: Unauthorized: resources.[cassandra_group](https://somerville.ed.ac.uk/project/stacks/stack/0fb3dcdd-6db6-4200-b511-5df63601906c/cassandra_group/).resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)
cassandra_group	e5cdfb6b-118b-416d-a06c-fe8042463134 	14 hours, 12 minutes 	Create Failed 	Unauthorized: resources.cassandra_group.resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)

**Comment by GregBlow** [comment] 2023-02-01 08:49
There appear to be two component problems:

1) Flavours with ephemeral disk (kafka) fail to create
2) Flavours with additional block storage (cassandra and sherlock) fail to complete, at least under certain circumstances.

Ephemeral disk test template:
[basicHeat_disk_varieties.txt](https://github.com/lsst-uk/somerville-operations/files/10555072/basicHeat_disk_varieties.txt)

**Comment by GregBlow** [comment] 2023-02-01 08:59
2023-02-01 08:43:58.144 21 INFO nova.scheduler.host_manager [req-7a96cbe7-1cec-48cd-9b88-fc246648d666 - - - - -] The instance sync for host 'sv-hpe-0-2' did not match. Re-created its InstanceList.

**Comment by GregBlow** [comment] 2023-02-01 09:08
kafka and kafka-test flavours still work when deploying a single instance in horizon.

**Comment by GregBlow** [comment] 2023-02-08 13:30
Michal has updated container images, however problem remains extant. Use of https://github.com/lsst-uk/somerville-operations/files/10555072/basicHeat_disk_varieties.txt fails, however setting kafka_flavor to 'small' rather than 'kafka_test' works.

**Comment by GregBlow** [comment] 2023-02-21 11:24
```
      block_device_mapping_v2:
        - device_name: sda
          volume_id: { get_resource: vol }
          delete_on_termination: true
```

```
suggested to change to 

      block_device_mapping_v2:
        - boot_index: -1
          device_type: disk
          delete_on_termination: false
          device_name: /dev/vdb
          ephemeral_format: ext4
          ephemeral_size: 800
        - volume_id: { get_resource: vol }
          delete_on_termination: true
```

**Comment by gpfrancis** [comment] 2023-02-21 11:47
Tried some tests - see https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1676978420802669

Attempting to deploy the Lasair stack with just a single kafka instance gave the following error:
```
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "Failure in updating stack: Resource UPDATE failed: resources.kafka_group: Resource CREATE failed: BadRequest: resources[0].resources.srv: Block Device Mapping is Invalid: failed to get volume d72aea40-8e8d-4eb3-9603-4dbb3f4dbe29. (HTTP 400) (Request-ID: req-750f4014-9b55-4ff8-b795-30afd4bc605f)"}
```

This is essentially the same error as trying to deploy any instance of any flavour, with or without additional attached volumes, currently produces.

My conclusion is that I am currently unable to test whether the change fixes the kafka-specific part of the problem because the general problem of being unable to create any instances at all is blocking, while noting that even if this change fixes the problem for the kafka flavour it likely also breaks the template for every other flavour.

**Comment by GregBlow** [comment] 2023-02-21 13:12
second (more complex) block device mapping:

```
block_device_mapping_v2:
        - boot_index: -1
          device_type: disk
          delete_on_termination: false
          device_name: /dev/vdb
          ephemeral_format: ext4
          ephemeral_size: 800  
		  volume_id: { get_resource: vol }
          delete_on_termination: true
```

**Comment by GregBlow** [comment] 2023-02-21 14:16
setting `device name = /sda` fails

**Comment by GregBlow** [comment] 2023-02-21 15:45
device_name = sda is set at https://raw.githubusercontent.com/lsst-uk/lasair-deploy/develop/server_with_volume.yaml, which is referenced as the `type` of the `resource`. This `type` works for all other flavours.

**Comment by GregBlow** [comment] 2023-02-21 16:21
Not setting `device_name` in the template allows the instance to boot with the `kafka` and `kafka-test` flavors. 

```
ubuntu@issue-66-test-14-server-a3wgikz3z4j7:~$ sudo fdisk -l
Disk /dev/loop0: 61.92 MiB, 64925696 bytes, 126808 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop1: 79.95 MiB, 83832832 bytes, 163736 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop2: 44.7 MiB, 46870528 bytes, 91544 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/vda: 25 GiB, 26843545600 bytes, 52428800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 1632EDC1-5D6E-4B1A-9DF5-D1C3D193B0F3

Device      Start      End  Sectors  Size Type
/dev/vda1  227328 52428766 52201439 24.9G Linux filesystem
/dev/vda14   2048    10239     8192    4M BIOS boot
/dev/vda15  10240   227327   217088  106M EFI System

Partition table entries are not in disk order.


Disk /dev/vdb: 1000 GiB, 1073741824000 bytes, 2097152000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

**Comment by GregBlow** [comment] 2023-02-21 16:26
setting `device_name` to `/dev/vda` both successfully creates and allows the instance to boot successfully.

I think the next step is to use a local copy of https://github.com/lsst-uk/lasair-deploy/blob/main/server_with_volume.yaml with that substitution in place with the lasair template (modified experimentally) and check the results.

**Comment by GregBlow** [comment] 2023-02-21 16:52
note: I have increased qserv project RAM by 25% to facilitate testing.

**Comment by GregBlow** [comment] 2023-02-21 17:21
setting `device_name`  does not simply fix the lasair-perf template:

```
Create Failed

Resource Create Failed: Badrequest: Resources.Kafka Group.Resources[0].Resources.Srv: Block Device Mapping Is Invalid: Failed To Get Volume C9d6a1e3-B425-441b-8189-Bb09a15dea26. (Http 400) (Request-Id: Req-Bfd1320e-3038-4f4a-Ac0e-De77478f1714)
```

**Comment by GregBlow** [comment] 2023-02-27 15:04
A peculiarity is that a very stripped down version of the lasair template merged into the working test template seems to break both resources, including the test server that works on it's own. 
[basicHeat_disk_varieties_lasair_hybrid(1).txt](https://github.com/lsst-uk/somerville-operations/files/10840996/basicHeat_disk_varieties_lasair_hybrid.1.txt)

**Comment by GregBlow** [comment] 2023-02-28 11:18
[basicHeat_disk_varieties_lasair_hybrid(2).txt](https://github.com/lsst-uk/somerville-operations/files/10849600/basicHeat_disk_varieties_lasair_hybrid.2.txt)
https://github.com/lsst-uk/somerville-operations/blob/main/test_data/server_with_volume_vt2.yaml

In this example, the lasair resource type has been stripped down sufficient to get it to work, while the resource based on  server_with_volume_vt1.yaml still does not work.

**Comment by GregBlow** [comment] 2023-02-28 11:20
ok, a little more progress today: 

I've stripped back the server_with_volume.yaml to work when provisioning single servers.

https://github.com/lsst-uk/somerville-operations/blob/main/test_data/server_with_volume_vt2.yaml

Still not fit for purpose. I'm going to try adding parts of vt1 (which is closer to the unmodified version) until the single server implementation breaks. If it doesn't it'll mean there is likely a problem with the OS::Heat::ResourceGroup implementation.

**Comment by GregBlow** [comment] 2023-03-01 10:33
have managed to get a working OS::Heat::ResourceGroup implementation
https://github.com/lsst-uk/somerville-operations/blob/main/test_data/server_with_volume_vt3.yaml

[basicHeat_disk_varieties_lasair_hybrid(4).txt](https://github.com/lsst-uk/somerville-operations/files/10859959/basicHeat_disk_varieties_lasair_hybrid.4.txt)

**Comment by GregBlow** [comment] 2023-03-01 12:25
![minimalDiff](https://user-images.githubusercontent.com/2021333/222138479-39d524e1-3356-486a-ab44-b667d1cea4e4.jpg)

Unexpectedly, minimal difference in working and broken kafka instances amount to network provision elements? Need to drill further.

**Comment by GregBlow** [comment] 2023-03-01 12:46
iterating down, network property remains only significant difference (all other differences are newlines)
![minimalDiff](https://user-images.githubusercontent.com/2021333/222143349-61dbb507-0c56-4d93-bac8-ac3f40aa82e2.jpg)

**Comment by GregBlow** [comment] 2023-03-01 13:54
![minimalDiff](https://user-images.githubusercontent.com/2021333/222159892-6da4d0e8-94f8-47fd-9cd7-8d8bb93ea3bb.jpg)

**Comment by GregBlow** [comment] 2023-03-01 14:56
[basicHeat_disk_varieties_lasair_hybrid(4).txt](https://github.com/lsst-uk/somerville-operations/files/10862266/basicHeat_disk_varieties_lasair_hybrid.4.txt)

Of the three resources assigned to the kafka_server_group it appears one selected randomly fails and two succeed reliably.

Volumes appear like this:

![image](https://user-images.githubusercontent.com/2021333/222176421-83788b06-c97e-4343-b6e8-e24f5be44903.png)

Might be issue of correctly labelling the server? Will try without variable.

**Comment by GregBlow** [comment] 2023-03-01 15:36
Trying to deploy this template repeatedly makes a random one of the three resources on the kafka_server_group resource declare that it has failed to create with the reason that block device is invalid. 

In the example heat stack the simple test instance (most divergent from the lasair template) was that one. 

When I add an additional resource, a randomly selected two fail. 

When I remove the plain OS::Nova::Server and OS::Cinder::Volume resources (that always create successfully), three of the four custom type resources, instead of two, deploy successfully.

**Comment by GregBlow** [comment] 2023-03-01 15:39
If count = 3 is set on a single resource and all others disabled, it deploys successfully, so iteration is working.

**Comment by GregBlow** [comment] 2023-03-01 16:23
Lasair problem template successfully deploys a single kafka node using vt4
[basicHeat_disk_varieties_lasair_hybrid(4).txt](https://github.com/lsst-uk/somerville-operations/files/10863282/basicHeat_disk_varieties_lasair_hybrid.4.txt)

**Comment by GregBlow** [comment] 2023-03-02 13:49
kafka flavour is 8TB, hypervisor disk is 10.8TB.

With this information in mind, finalise kafka fix and move onto other problem elements.

**Comment by GregBlow** [comment] 2023-03-03 10:50
[basicHeat_disk_varieties_lasair_hybrid(7).txt](https://github.com/lsst-uk/somerville-operations/files/10881119/basicHeat_disk_varieties_lasair_hybrid.7.txt)

**Closed** 2023-04-18 09:40 UTC
